import streamlit as st

logger = st.logger.get_logger("micronarratives")


def display_identity_page(text, editable, previous_required, table):
    """
    Display the participant ID collection page.

    Creates a Streamlit page that prompts the user to enter their participant ID. It
    first attempts to extract the ID from URL parameters, and if available, pre-fills
    the input field with this value. If a previous scenario is required, a participant
    will not be permitted to move on from this page until a participant ID that has an
    associated previous scenario is provided.

    Args:
        text (str): Optional text shown before ID input box
        editable (bool): Whether the pre-filled ID should be editable
        previous_required (bool): Whether there must be a previous scenario associated
            with this participant ID
        table (DynamoDB.Table | None): Table from where the previous scenario should be
            read (if required)

    Returns:
        str | None: The participant ID entered by the user
        str | None: The participant's previous scenario
    """
    st.markdown("#### Participant Identification")

    # Get ID from URL parameter if available
    query_params = st.query_params
    default_id = query_params.get("pid", "") or query_params.get("participant_id", "")

    # Use a form to require explicit submission
    with st.form(key="participant_form"):
        if text:
            st.write(text)

        participant_id = st.text_input(
            "Enter your participant ID:",
            value=default_id,
            key="participant_id_input",
            disabled=not editable,
        ).strip()

        submit_button = st.form_submit_button("Confirm ID")

    if submit_button and participant_id:
        previous_scenario = None

        if previous_required:
            previous_scenario = get_previous_scenario_from_db(table, participant_id)

            if previous_scenario is None:
                st.error(
                    "We weren't able to find a previous response for participant ID "
                    f"*{participant_id}*. Please check your participant ID or contact "
                    "your study administrator.",
                    icon="❗",
                )

                return None, None
        return participant_id, previous_scenario

    return None, None


def get_participant_data(llm_prompts, table=None):
    """
    Gets participant ID and (if needed), their previous response, then updates session
    state accordingly.

    Based on settings in llm_prompts, this function obtains a participant ID either by:
    1. Using the session ID if participant ID is not required
    2. Collecting the ID from the user through the display_identity_page function

    Once a valid ID is obtained, the function updates the session state with the ID
    and (optionally) previous scenario text, then advances the application state to the
    next step ("conversation").

    Args:
        llm_prompts (LLMConfig): Configuration object containing prompts, settings,
            and a flag indicating whether a participant ID is required.
        table (DynamoDB.Table | None) : Table from which a participant's previous
            scenario should be taken.
    """

    url_participant_id = st.query_params.get("pid") or st.query_params.get(
        "participant_id"
    )
    if isinstance(url_participant_id, list):
        url_participant_id = url_participant_id[0] if url_participant_id else ""

    if url_participant_id:
        participant_id = str(url_participant_id).strip()
        previous_scenario = None
    elif llm_prompts.require_participant_id:
        participant_id, previous_scenario = display_identity_page(
            llm_prompts.participant_collection_text,
            llm_prompts.editable_participant_id,
            False,
            table,
        )
    else:
        participant_id = st.session_state["session_id"]
        previous_scenario = None

    # Once participant ID is either provided by the user or set to the same
    # value as session ID, equal, set agentState to "conversation"
    if participant_id:
        st.session_state["participant_id"] = participant_id
        st.session_state["previous_scenario"] = previous_scenario
        logger.info(
            f"User {st.session_state['participant_id']}: Participant ID confirmed"
        )
        st.session_state["agentState"] = "collect"
        st.rerun()


def get_previous_scenario_from_db(table, participant_id):
    """
    Obtains a scenario generated by the same participant during an earlier interaction
    with an instance of a micro-narratives app.
    if table is None or not participant_id:
        return None
    Args:
        table (DynamoDB.Table): table from where previous data will be read
        participant_id (str): unique identifier for a particular participant

    Returns:
        str | None: text of the participant's selected scenario, if available

    """

    # Use scan with a filter instead of query (query would require us to
    # know a table's primary key structure, or create additional indices –
    # something we want to be agnostic about/don't want to be forced to do).
    participant_records = table.scan(
        FilterExpression="participant_id = :pid",
        ExpressionAttributeValues={":pid": participant_id},
        # Include completion_time in the projection to sort by
        ProjectionExpression="participant_id, final_scenario, completion_time",
    )

    if participant_records["Items"]:
        sorted_items = sorted(
            participant_records["Items"],
            key=lambda x: x.get("completion_time", ""),
            reverse=True,
        )
        previous_final_scenarios = [
            r["final_scenario"] for r in sorted_items if r["final_scenario"]
        ]

        if num_scenarios := len(previous_final_scenarios):
            logger.info(
                f"User {participant_id}: Found {num_scenarios} previous scenarios from "
                f"{len(sorted_items)} database entries; using latest"
            )
            return previous_final_scenarios[0]

    logger.info(f"User {participant_id}: No previous scenarios found")
    return None
