from concurrent.futures import ThreadPoolExecutor, as_completed

import streamlit as st
from langchain.output_parsers.json import SimpleJsonOutputParser

try:
    from langsmith.run_helpers import get_current_run_tree
except ImportError:
    get_current_run_tree = None

logger = st.logger.get_logger("micronarratives")


def generate_summary(llm_prompts, msgs, extraction_chain, testing):
    """
    Generate a dictionary containing a summary of the key points of the conversation.
    The LLM-generated dictionary is not guaranteed to contain the keys specified in the
    configuration file, so this function pulls out the required keys and leaves them
    blank if a corresponding key-value pair was not generated by the LLM as a result of
    the conversation.
    """

    if testing:
        logger.info(
            f"User {st.session_state['participant_id']}: Using testing messages"
        )
        message_history = llm_prompts.one_shot_conversation
    else:
        message_history = msgs

    answer_set = extraction_chain.invoke({"conversation_history": message_history})
    summary_answers = {key: answer_set.get(key, "") for key in llm_prompts.summary_keys}
    st.session_state["summary_answers"] = summary_answers

    return summary_answers


def generate_scenarios(llm_prompts, chat_model, summary_answers, bar):
    """
    Generates the scenarios from the user's summary answers, in the style of each of the
    personas. As scenarios are generated, updates the progress bar.
    """

    scenario_chain = (
        llm_prompts.scenario_prompt_template | chat_model | SimpleJsonOutputParser()
    )

    def generate_single(persona):
        response = scenario_chain.invoke({"persona": persona} | summary_answers)
        if not isinstance(response, dict) or "output_scenario" not in response:
            raise ValueError(f"Unexpected response format: {response}")
        return response["output_scenario"]

    scenarios = [None] * len(llm_prompts.personas)
    completed = 0

    with ThreadPoolExecutor(max_workers=min(3, len(llm_prompts.personas))) as executor:
        future_to_index = {
            executor.submit(generate_single, persona): index
            for index, persona in enumerate(llm_prompts.personas)
        }

        for future in as_completed(future_to_index):
            index = future_to_index[future]
            try:
                scenarios[index] = future.result()
            except Exception as exc:
                logger.error(f"Error generating scenario {index}: {exc}")
                scenarios[index] = (
                    "Sorry, something went wrong while generating this scenario."
                )

            completed += 1
            bar.progress(
                completed / len(llm_prompts.personas),
                f"Processed scenario {completed} of {len(llm_prompts.personas)}",
            )

    return scenarios


def generate_scenarios_with_progress(
    llm_prompts,
    chat_model,
    summary_answers,
    langsmith_enabled=False,
):
    """Set up the Streamlit page for scenario generation and return the results."""

    st.markdown("#### Summarising your story")
    messages_container = st.container(border=True)

    with messages_container:
        st.chat_message("ai").write(
            "Seems I have everything! "
            "Let me try to summarise what you said in three scenarios. "
            "See if you like any of these!"
        )
        bar = st.progress(0, text="Processing your scenarios")
        scenarios = generate_scenarios(llm_prompts, chat_model, summary_answers, bar)
        st.session_state["generated_scenarios"] = scenarios

    st.session_state["langsmith_run_id"] = None
    if langsmith_enabled and get_current_run_tree is not None:
        run_tree = get_current_run_tree()
        if run_tree is not None:
            st.session_state["langsmith_run_id"] = run_tree.id

    return scenarios


def select_scenario(index):
    """Store the index of the selected scenario."""
    st.session_state["selected_scenario_index"] = index


def rate_selected_scenario():
    """Display the selected scenario and collect a 0-10 rating."""

    selected_index = st.session_state["selected_scenario_index"]
    scenario_text = st.session_state["generated_scenarios"][selected_index]

    container = st.container(border=True)
    with container:
        st.markdown(scenario_text)
        st.markdown(
            "<div style='font-size:1.5em; font-weight:bold; font-style:italic;'>"
            "How close is this to what I want to say?"
            "</div>",
            unsafe_allow_html=True,
        )
        st.markdown(
            """
            <div
                style="display: flex; justify-content: space-between; margin-top: -8px;"
            >
                <span style="color: red;">needs a lot of work</span>
                <span style="color: green;">this looks good</span>
            </div>
            """,
            unsafe_allow_html=True,
        )

        rating = st.slider(
            "How would you rate this scenario?",
            min_value=0,
            max_value=10,
            value=5,
            step=1,
            label_visibility="collapsed",
            format=" ",
        )
        st.session_state["selected_scenario_review"] = (
            rating
        )

        _, center_col, _ = st.columns([1, 2, 1])
        with center_col:
            if st.button("Continue", use_container_width=True):
                st.session_state["final_scenario"] = scenario_text
                st.session_state["final_scenario_editor"] = scenario_text
                if rating == 10:
                    st.session_state["agentState"] = "save"
                else:
                    st.session_state["agentState"] = "adapt"
                st.rerun()


def click_selection_yes(index):
    """Compatibility wrapper for older selection flow."""
    select_scenario(index)


def click_selection_no(index):
    """Compatibility wrapper for older selection flow."""
    st.session_state["scenario_judgement"][index] = ""


def sliderChange(slider_name, index):
    """Compatibility wrapper for older selection flow."""
    st.session_state["scenario_judgement"][index] = st.session_state[slider_name]


def scenario_selection(popover, index):
    """Compatibility wrapper retaining the older popover entry point."""
    with popover:
        st.button(
            "Continue with this scenario 🎉",
            key=f"yeskey_{index}",
            on_click=select_scenario,
            args=(index,),
            use_container_width=True,
        )
